### ISSUE TITLE
getting errors

### ISSUE THREAD

**Issue by leonglo** [Zennara/ManageInvites#3]
getting these errors when runnin
`i/help` and `i/iroles`

`Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/runner/ManageInvites/venv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 192, in on_message
    prefix = db[str(message.guild.id)]["prefix"]
  File "/home/runner/ManageInvites/venv/lib/python3.8/site-packages/replit/database/database.py", line 439, in __getitem__
    raw_val = self.get_raw(key)
  File "/home/runner/ManageInvites/venv/lib/python3.8/site-packages/replit/database/database.py", line 479, in get_raw
    raise KeyError(key)
KeyError: '979790913096253511'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/runner/ManageInvites/venv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 192, in on_message
    prefix = db[str(message.guild.id)]["prefix"]
  File "/home/runner/ManageInvites/venv/lib/python3.8/site-packages/replit/database/database.py", line 439, in __getitem__
    raw_val = self.get_raw(key)
  File "/home/runner/ManageInvites/venv/lib/python3.8/site-packages/replit/database/database.py", line 479, in get_raw
    raise KeyError(key)
KeyError: '979790913096253511'`

**Comment by Zennara** [comment]
I no longer support this bot, but the advice I could give you would be to host it on repl.it as that is what I used when creating it. However repl.it is not really viable anymore for reliable hosting.
